name: 'Crawford Ifland '
favicon: null
layout_spectrum: 0.1989247
typography_spectrum: 0.7168459
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Crawford Ifland
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#31303e'
    - '#fa7900'
    - '#c26511'
    - '#864f24'
    - '#553d33'
  brandStrength: 1
  lightness: 1
  saturation: 0
  rhythmicContrast: 1
purpose: []
