name: 'Crawford Ifland '
favicon: null
layout_spectrum: 0.1989247
typography_spectrum: 0.7168459
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Crawford Ifland
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020303'
    - '#3A4164'
    - '#776D89'
    - '#C7B39B'
    - '#AC3730'
  brandStrength: 0
  lightness: 1
  saturation: 0
  rhythmicContrast: 1
purpose: []
